spring.application.name=test-api
server.port=9090

# PostgreSQL 접속 정보
spring.datasource.url=jdbc:postgresql://localhost:5433/testdb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# redis 접속 정보
spring.data.redis.host=localhost
spring.data.redis.port=6223

# JPA 설정
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8