services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "1234"
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6223:6379"

volumes:
  pgdata:
    external: true
    name: bdf48958f624d486ee4090d6495cec3d8078f7db3a4709b35d914ba94da498e4